import type { Metadata } from "next";
import "./globals.css";
import { UserContextProvider } from "./user-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <UserContextProvider>{children}</UserContextProvider>
      </body>
    </html>
  );
}
